development:
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://redistogo:2308d8051c7eef513f21db696be34d2a@crestfish.redistogo.com:10417/
